"""
Comment formatters and helpers for autonomous agent issue/PR interactions.
Standardizes headers, footers, badges, and automated metadata disclaimers across all comments.
"""
from typing import Optional

# Standard Agent Header Badges
BADGE_AUTONOMOUS_AGENT = "🤖 **Autonomous Agent**"
BADGE_AGENT_UPDATE = "🤖 **Agent Update**"
BADGE_AGENT_TAKEOVER = "🤖 **Agent Takeover: Development Started**"
BADGE_AGENT_PAUSED = "🤖 **Agent Paused**"

# Standard Metadata Disclaimer Footer
FOOTER_SIGNATURE = "Posted automatically by Agent Manager"


def format_agent_metadata_footer(
    session_id: Optional[str] = None,
    worktree_path: Optional[str] = None,
    git_branch: Optional[str] = None
) -> str:
    """
    Constructs a standardized metadata footer indicating the automated nature
    of the comment, the associated worktree/branch, and the session context.
    """
    metadata_parts = [f"*{FOOTER_SIGNATURE}"]
    if session_id:
        metadata_parts.append(f"Session: `{session_id}`")
    if git_branch:
        metadata_parts.append(f"Branch: `{git_branch}`")
    if worktree_path:
        metadata_parts.append(f"Worktree: `{worktree_path}`")

    return f"\n\n---\n{' | '.join(metadata_parts)}*"


def format_agent_comment(
    body: str,
    header: Optional[str] = None,
    session_id: Optional[str] = None,
    worktree_path: Optional[str] = None,
    git_branch: Optional[str] = None
) -> str:
    """
    Wraps comment content with the standardized header badge and metadata footer.
    """
    clean_body = body.strip()
    active_header = header or BADGE_AUTONOMOUS_AGENT
    footer = format_agent_metadata_footer(
        session_id=session_id,
        worktree_path=worktree_path,
        git_branch=git_branch
    )

    if clean_body.startswith("🤖 **"):
        # If the body already has a standard agent header badge, avoid duplicating it
        return f"{clean_body}{footer}"

    return f"{active_header}\n\n{clean_body}{footer}"


def is_agent_comment(body: Optional[str]) -> bool:
    """
    Reliably detects whether a comment was generated by an autonomous agent
    or the Agent Manager system across all automated post variations.
    """
    if not body:
        return False

    stripped = body.strip()

    # Detect standardized header badges / prefixes
    if (
        stripped.startswith("🤖 **Agent")
        or stripped.startswith("🤖 **Autonomous Agent")
        or stripped.startswith("🚀 **Task Complete")
    ):
        return True

    # Detect pause notifications
    if (
        stripped.startswith("⚠️ **Task Paused")
        or "### 🛑 Repetitive Tool Loop Detected" in stripped
        or "### 📊 Task Insights" in stripped
    ):
        return True

    # Detect standardized metadata footer signature
    if FOOTER_SIGNATURE in stripped:
        return True

    return False
