"""initial_session_and_message_schema

Revision ID: 0f31358a5561
Revises: 
Create Date: 2026-10-05 20:04:11.018891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f31358a5561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('repo', sa.String(length=255), nullable=True),
    sa.Column('issue_number', sa.Integer(), nullable=True),
    sa.Column('pr_url', sa.String(length=512), nullable=True),
    sa.Column('pr_number', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('worktree_path', sa.String(length=1024), nullable=True),
    sa.Column('git_branch', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.Column('turn_count', sa.Integer(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('consecutive_duplicate_tool_count', sa.Integer(), nullable=False),
    sa.Column('consecutive_view_file_count', sa.Integer(), nullable=False),
    sa.Column('last_tool_signature', sa.String(length=255), nullable=True),
    sa.Column('circuit_breaker_triggered', sa.Boolean(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('thinking_tokens', sa.Integer(), nullable=False),
    sa.Column('cache_read_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('quota_percent', sa.Float(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('agy_mode', sa.String(length=64), nullable=False),
    sa.Column('terminal_command', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('effort', sa.String(length=64), nullable=True),
    sa.Column('current_activity', sa.String(length=128), nullable=True),
    sa.Column('last_activity_at', sa.String(length=64), nullable=True),
    sa.Column('is_stalled', sa.Boolean(), nullable=False),
    sa.Column('quota_exceeded', sa.Boolean(), nullable=False),
    sa.Column('quota_message', sa.Text(), nullable=True),
    sa.Column('seen_comment_ids_json', sa.Text(), nullable=True),
    sa.Column('last_issue_body', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.String(length=64), nullable=True),
    sa.Column('is_compacted', sa.Boolean(), nullable=False),
    sa.Column('compact_summary', sa.Text(), nullable=True),
    sa.Column('workflow_pipeline_enabled', sa.Boolean(), nullable=False),
    sa.Column('workflow_stage', sa.String(length=64), nullable=False),
    sa.Column('pipeline_summary', sa.Text(), nullable=True),
    sa.Column('pipeline_plan', sa.Text(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('stream_log_file', sa.Text(), nullable=True),
    sa.Column('exit_code_file', sa.Text(), nullable=True),
    sa.Column('stream_log_offset', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_agent_sessions_is_archived'), 'agent_sessions', ['is_archived'], unique=False)
    op.create_index(op.f('ix_agent_sessions_issue_number'), 'agent_sessions', ['issue_number'], unique=False)
    op.create_index(op.f('ix_agent_sessions_repo'), 'agent_sessions', ['repo'], unique=False)
    op.create_index(op.f('ix_agent_sessions_session_id'), 'agent_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_status'), 'agent_sessions', ['status'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('order_idx', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.String(length=64), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('tool_args_json', sa.Text(), nullable=True),
    sa.Column('tool_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_session_order', 'conversation_messages', ['session_id', 'order_idx'], unique=False)
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_index('idx_messages_session_order', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_agent_sessions_status'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_session_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_repo'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_issue_number'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_is_archived'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    # ### end Alembic commands ###
